declare module "*cors"
declare module "*express"
declare module "*mongoose"
declare module "*ejs"
declare module "*googleapis";
declare module "*bcrypt";
declare module "*slugify";
declare module "*jsonwebtoken";
declare module "*cloudinary";
declare module "*multer";
declare module "*flutterwave-node-v3";
declare module "*nodemailer";
declare module "*uuid";